[package]
name = "AI2048"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"
opt-level = 3
lto = "thin"

[dependencies]
rand = "*"
clearscreen = "*"
rayon = '*'
num_cpus = '*'
